### ISSUE TITLE
run_model_bpa Running Forever and Not Completing for Certain Datasets

### ISSUE THREAD

**Issue by Jai-Prakash-HU** [microsoft/semantic-link-labs#280] opened 2024-11-15 17:09 UTC
1. Tried multiple times, this particular dataset never gets completed.
2. Tried with both function run_model_bpa and run_model_bpa_bulk
3. published dadatset to diffrent workspace, same result
4. Dataset is very simple
5. I tried 7-8 times on different days same result.
6. It doesn't throw any error, just keeps running.
7. Same function in the same connection instance running fine.
8. I can download dataset, it looks fine. I published it to different workspace with different name, but same issue.
9. Model Size: 113 MB
10. It is happening with many datasets. Like 2 out of 10 datasets. 

![Image](https://github.com/user-attachments/assets/01eaf7af-e89b-4428-a1e1-8326f85d1677)

![Image](https://github.com/user-attachments/assets/0d41d92e-abf4-47e1-84f0-2b1ea0e68535)

![Image](https://github.com/user-attachments/assets/f15892ae-4bcf-462a-b3fc-6f07b3ba2731)

![Image](https://github.com/user-attachments/assets/695f53a7-2b00-4629-a72a-8bec929f7d7b)

![Image](https://github.com/user-attachments/assets/243a0af9-792e-4e6b-b550-d2816ec905ae)

**Comment by Jai-Prakash-HU** [comment] 2024-11-17 03:28
Also, one more unusual error after lates version of release as below.  **_multiple repeat at position 42_**


![Image](https://github.com/user-attachments/assets/17d4f1d4-ef0b-4687-86c9-23689a08233a)

**Comment by m-kovalsky** [comment] 2024-11-17 12:21
For the 'multiple repeat at position 42' error, run this model against the run_model_bpa function and provide the full error message.

For the unending issue - do you have some sort of circular dependency in your DAX? For example, Measure A depends on Measure B and Measure B depends on Measure A.

**Comment by m-kovalsky** [comment] 2024-11-18 13:06
For the 42 error, I will likely need to see the .bim file as this error message is not proving useful.

Regarding the dependencies issue, does the labs.get_measure_dependencies() function work for that semantic model?

**Comment by Jai-Prakash-HU** [comment] 2024-11-18 23:31
labs.get_measure_dependencies() function works fine


![Image](https://github.com/user-attachments/assets/e6cd86d8-8104-4fbd-9623-85b6ecfaf82d)

**Comment by Jai-Prakash-HU** [comment] 2024-11-20 15:44
As it is getting stuck, and I am not able to use it in an automation. Could you please introduce a timeout optional parameter so I can pass it like 300 seconds or 6000 seconds for workspace to timeout for now. So it will jump to next workspace if it or getting stuck at any workspace or dataset. 

i am trying externally to terminate it with some timeout but function is blocking, and timeout termination is not getting executed.

**Comment by m-kovalsky** [comment] 2024-11-20 18:37
Do you have an issue when running model calc dependencies when using semantic link labs version 0.8.3?

I don’t plan to put a timeout. I plan to solve the root cause. To do that, I need to figure out what about this model is causing the model calc dependencies function to go on an infinite loop.

**Comment by Jai-Prakash-HU** [comment] 2024-11-28 20:01
I need some more time to get the exact case when it stuck. I will update here.

**Comment by Jai-Prakash-HU** [comment] 2024-11-29 02:42
Just an update a dataset was running for forever for below function in 8.3. Now that dataset is working fine in 8.8
get_model_calc_dependencies
run_model_bpa

But still some dataset getting stuck in 8.8 and some throwing error like below

Process Process-1:
Traceback (most recent call last):
  File "/home/trusted-service-user/cluster-env/clonedenv/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/trusted-service-user/cluster-env/clonedenv/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/ipykernel_11250/911325610.py", line 80, in run_bpa_for_workspace
    labs.run_model_bpa(dataset=Dataset_Name, workspace=Workspace_Name, export=True)
  File "/home/trusted-service-user/cluster-env/clonedenv/lib/python3.11/site-packages/sempy/_utils/_log.py", line 348, in log_decorator_wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/trusted-service-user/cluster-env/clonedenv/lib/python3.11/site-packages/sempy_labs/_model_bpa.py", line 314, in run_model_bpa
    x = [nm(obj) for obj in tom.model.Tables if expr(obj, tom)]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trusted-service-user/cluster-env/clonedenv/lib/python3.11/site-packages/sempy_labs/_model_bpa.py", line 314, in <listcomp>
    x = [nm(obj) for obj in tom.model.Tables if expr(obj, tom)]
                                                ^^^^^^^^^^^^^^
  File "/home/trusted-service-user/cluster-env/clonedenv/lib/python3.11/site-packages/sempy_labs/_model_bpa_rules.py", line 416, in <lambda>
    lambda obj, tom: any(
                     ^^^^
  File "/home/trusted-service-user/cluster-env/clonedenv/lib/python3.11/site-packages/sempy_labs/_model_bpa_rules.py", line 417, in <genexpr>
    re.search(
  File "/home/trusted-service-user/cluster-env/clonedenv/lib/python3.11/re/__init__.py", line 176, in search
    return _compile(pattern, flags).search(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trusted-service-user/cluster-env/clonedenv/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trusted-service-user/cluster-env/clonedenv/lib/python3.11/re/_compiler.py", line 745, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trusted-service-user/cluster-env/clonedenv/lib/python3.11/re/_parser.py", line 989, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trusted-service-user/cluster-env/clonedenv/lib/python3.11/re/_parser.py", line 464, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trusted-service-user/cluster-env/clonedenv/lib/python3.11/re/_parser.py", line 694, in _parse
    raise source.error("multiple repeat",
re.error: multiple repeat at position 42

**Comment by m-kovalsky** [comment] 2024-11-29 05:20
This is fixed in [0.8.8](https://github.com/microsoft/semantic-link-labs/releases/tag/0.8.8)

**Closed by m-kovalsky** 2024-11-29 05:20 UTC
Labels: bug
